sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: php

services:
  - xvfb

install:
  - nvm install 10
  - npm install
  - npm run install-all
  - ./node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager update

script:
  - npm run e2e


notifications:
  slack:
    secure: il37MYIBZBYqb4NhdnjwAaOpKoXnlUpxw39uVmViepKy2sbqJagMeiIuTDserDxw2edRCGJOg9ZyvKRQrUPBqB0/hTjQid8t6ZsL+b+60/hz7UOGHeULGOgZ4WtpHZXh3J17R9BARMNXBm2u768or3znITO2q6qJ4htdIQVwg/K6EZcrpaM4em02ZVamF5elxIguD35FCKJMMDiLZq61Y8sZhqahXcmzGrc60woYthCZ6gF9/n/pTE+GM01TpG+bbidtEQYKMoDe00zx8p8Ivl2mMIIFuoe/x8qoFcoUxNiq0LSRx2HWcNSIncT5U1lAZ6VNAhpmu+/y+G8Umk1engcGY3C+R1xNrbmQp4AJ2HHEMLjVrY9Uk26yVSQ/XAYxactNj3JxScpvROlOJOszp/eepSWrDP2/cTeRty4LDE/okwNeS8n4viOSDvyjVFwRdkaw3hKJnUHI2ea69a3GY+1+yXzI0VU3TItm01j4ovYr2NHv0ZKJivsa8s1etGAzun4NLpWXQK2JxmwZXM7tpeahr0y7TDKwtT3sbM3J1gH5B+AcCp0uhddHobFQW4g282ghPXdec20F6he4F8KNTpEs3ulucC/mU0V1C73MplOu3yv4SdS28R9DNS/qIroqRaRE34Hr5yDccoWwKs4OcEZCa8DOZu8lXa69h6v81oU=
